apiVersion: "kubeflow.org/v1beta1"
kind: TFJob
metadata:
  name: $app-$run
  labels:
    mlt-app-name: $app
spec:
  replicaSpecs:
    - replicas: $num_ps
      tfReplicaType: PS
      template:
        spec:
          containers:
            - image: $image
              name: tensorflow
#             ### BEGIN KSYNC SECTION
#             command: ['/bin/sh']
#             args: ['-c', 'python main.py; tail -f /dev/null']
#             ### END KSYNC SECTION
          restartPolicy: OnFailure
    - replicas: $num_workers
      tfReplicaType: WORKER
      template:
        spec:
          containers:
            - image: $image
              name: tensorflow
#             ### BEGIN KSYNC SECTION
#             command: ['/bin/sh']
#             args: ['-c', 'python main.py; tail -f /dev/null']
#             ### END KSYNC SECTION
          restartPolicy: OnFailure
  terminationPolicy:
    chief:
      replicaName: WORKER
      replicaIndex: 0
